# Generated by Django 3.1.2 on 2021-01-18 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_remove_fleetup_permission'),
        ('eveonline', '0012_index_additions'),
        ('opcalendar', '0015_eventimport_eve_character'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngameEvents',
            fields=[
                ('event_id', models.PositiveBigIntegerField(help_text='The EVE ID of the event', primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('duration', models.CharField(max_length=32)),
                ('importance', models.CharField(max_length=32)),
                ('owner_id', models.CharField(max_length=32)),
                ('owner_name', models.CharField(max_length=128)),
                ('owner_type', models.CharField(max_length=32)),
                ('response', models.TextField()),
                ('text', models.TextField()),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='whether this owner is currently included in the sync process')),
                ('character', models.ForeignKey(blank=True, default=None, help_text='character used for syncing blueprints', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='+', to='authentication.characterownership')),
                ('corporation', models.OneToOneField(blank=True, default=None, help_text="Corporation owning blueprints, if this is a 'corporate' owner", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eveonline.evecorporationinfo')),
            ],
        ),
    ]
