# Generated by Django 3.1.2 on 2021-01-18 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opcalendar', '0016_ingameevents_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='general',
            options={'default_permissions': (), 'managed': False, 'permissions': (('basic_access', 'Can access this app'), ('view_public', 'Can see public events'), ('view_member', 'Can see member events'), ('create_event', 'Can create and edit events'), ('manage_event', 'Can delete and manage signups'), ('add_ingame_calendar_owner', 'Can add ingame calendar feeds for their corporation'))},
        ),
    ]
