# Generated by Django 3.1.2 on 2021-01-19 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opcalendar', '0017_auto_20210118_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingameevents',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='ingameevents',
            name='owner',
            field=models.ForeignKey(default=2, help_text='Event holder', on_delete=django.db.models.deletion.CASCADE, to='opcalendar.owner'),
            preserve_default=False,
        ),
    ]
