# Generated by Django 3.1.2 on 2021-01-19 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opcalendar', '0018_auto_20210119_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingameevents',
            old_name='date',
            new_name='event_date',
        ),
        migrations.RemoveField(
            model_name='ingameevents',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='ingameevents',
            name='importance',
        ),
        migrations.RemoveField(
            model_name='ingameevents',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='ingameevents',
            name='owner_type',
        ),
        migrations.RemoveField(
            model_name='ingameevents',
            name='response',
        ),
        migrations.RemoveField(
            model_name='ingameevents',
            name='text',
        ),
    ]
