# Generated by Django 3.1.2 on 2021-01-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcalendar', '0019_auto_20210119_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingameevents',
            name='duration',
            field=models.CharField(default=2, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingameevents',
            name='owner_name',
            field=models.CharField(default='ikarus', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingameevents',
            name='owner_type',
            field=models.CharField(default='character', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingameevents',
            name='text',
            field=models.TextField(default='tect stet'),
            preserve_default=False,
        ),
    ]
