# Generated by Django 3.1.5 on 2021-01-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcalendar', '0020_auto_20210125_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimport',
            name='source',
            field=models.CharField(choices=[('SF', 'Spectre Fleet'), ('EU', 'EVE University'), ('FI', 'Fun Inc.')], help_text='The API source where you want to pull events from', max_length=32),
        ),
    ]
