# Generated by Django 3.1.2 on 2021-01-19 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opcalendar', '0020_auto_20210119_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingameevents',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='ingameevents',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='ingameevents',
            name='owner_type',
        ),
        migrations.RemoveField(
            model_name='ingameevents',
            name='text',
        ),
    ]
