# Generated by Django 3.1.2 on 2021-01-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcalendar', '0021_auto_20210119_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingameevents',
            name='duration',
            field=models.CharField(default='2', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingameevents',
            name='importance',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingameevents',
            name='owner_name',
            field=models.CharField(default='iki', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingameevents',
            name='owner_type',
            field=models.CharField(default='corporation', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingameevents',
            name='text',
            field=models.TextField(default='tetet'),
            preserve_default=False,
        ),
    ]
