# Generated by Django 3.1.2 on 2021-01-19 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opcalendar', '0022_auto_20210119_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='general',
            options={'default_permissions': (), 'managed': False, 'permissions': (('basic_access', 'Can access this app'), ('view_public', 'Can see public events'), ('view_member', 'Can see member events'), ('view_ingame', 'Can see events from ingame calendar'), ('create_event', 'Can create and edit events'), ('manage_event', 'Can delete and manage signups'), ('add_ingame_calendar_owner', 'Can add ingame calendar feeds for their corporation'))},
        ),
    ]
