# Generated by Django 3.1.7 on 2021-03-30 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opcalendar', '0023_auto_20210324_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='general',
            options={'default_permissions': (), 'managed': False, 'permissions': (('basic_access', 'Can access this app and see operations based on visibility rules'), ('create_event', 'Can create and edit events'), ('see_signups', 'Can see all signups for event'), ('manage_event', 'Can delete and manage other signups'), ('add_ingame_calendar_owner', 'Can add ingame calendar feeds for their corporation'))},
        ),
        migrations.AddField(
            model_name='ingameevents',
            name='host',
            field=models.ForeignKey(default=1, help_text='Host entity for the event', on_delete=django.db.models.deletion.CASCADE, to='opcalendar.eventhost'),
        ),
        migrations.AlterField(
            model_name='eventhost',
            name='website',
            field=models.CharField(blank=True, help_text='Website link URL', max_length=150),
        ),
    ]
