# Generated by Django 3.1.7 on 2021-04-07 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opcalendar', '0023_auto_20210330_0632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingameevents',
            name='moon_extraction',
        ),
    ]
