# Generated by Django 3.1.2 on 2021-03-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('opcalendar', '0024_auto_20210223_0648'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventVisibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the filter', max_length=150)),
                ('is_active', models.BooleanField(default=True, help_text='whether this owner is currently included in the sync process')),
                ('restricted_to_group', models.ManyToManyField(blank=True, help_text='Restrict event visibility to the following group(s) ...', related_name='eventvisibility_require_groups', to='auth.Group')),
            ],
        ),
    ]
