# Generated by Django 3.1.2 on 2021-04-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opcalendar", "0025_eventvisibility_include_in_feed"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventvisibility",
            name="is_visible",
            field=models.BooleanField(
                default=True,
                help_text="Whether this visibility filter should be displayed on the event form. Disable for internal visibilities such as the NPSI import fleet visibilities.",
            ),
        ),
    ]
