# Generated by Django 4.2.11 on 2024-05-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcalendar', '0026_alter_event_repeat_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmember',
            name='status',
            field=models.CharField(choices=[('A', 'Attending'), ('M', 'Maybe'), ('D', 'Declined')], default='A', max_length=1),
        ),
    ]
