# Generated by Django 3.1.2 on 2021-04-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcalendar', '0026_eventvisibility_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventvisibility',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Whether this visibility filter is used as the default value on the event form'),
        ),
    ]
