# Generated by Django 3.1.2 on 2021-03-14 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opcalendar', '0026_event_restricted_to_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='restricted_to_group',
        ),
        migrations.AddField(
            model_name='event',
            name='restricted_to_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opcalendar.eventvisibility'),
        ),
    ]
