# Generated by Django 3.1.2 on 2021-04-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opcalendar", "0027_eventvisibility_is_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventhost",
            name="is_default",
            field=models.BooleanField(
                default=False,
                help_text="Whether this host is used as the default value on the event form",
            ),
        ),
    ]
