# Generated by Django 3.1.2 on 2021-03-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('opcalendar', '0027_auto_20210314_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='restricted_to_group',
        ),
        migrations.AddField(
            model_name='event',
            name='restricted_to_group',
            field=models.ManyToManyField(blank=True, help_text='Restrict ping rights to the following group(s) ...', related_name='event_require_groups', to='auth.Group'),
        ),
    ]
