# Generated by Django 4.2 on 2025-09-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opcalendar", "0027_eventmember_comment_eventmember_status_usersettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="timezone",
            field=models.CharField(
                default="UTC",
                max_length=64,
                verbose_name="Timezone",
                help_text=(
                    "IANA timezone name, e.g. Europe/London, America/New_York, Australia/Sydney"
                ),
            ),
        ),
        migrations.RemoveField(
            model_name="usersettings",
            name="use_local_times",
        ),
    ]
