# Generated by Django 4.2.11 on 2024-05-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opcalendar", "0027_eventmember_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventmember",
            name="comment",
            field=models.CharField(
                blank=True, help_text="Optional comment about the event", max_length=100
            ),
        ),
    ]
