# Generated by Django 4.2.23 on 2026-02-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcalendar', '0028_usersettings_timezone_remove_use_local_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='repeat_event',
            field=models.CharField(blank=True, choices=[('DD', 'Daily'), ('WE', 'Weekly'), ('FN', 'Fortnightly'), ('MM', 'Monthly'), ('YY', 'Yearly')], default=False, help_text='Select if you want to repeat this event in the future', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='timezone',
            field=models.CharField(default='UTC', max_length=64, verbose_name='Timezone'),
        ),
    ]
