# Generated by Django 3.1.2 on 2021-03-15 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("opcalendar", "0028_auto_20210314_1220"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="doctrine",
            field=models.CharField(
                default="", help_text="Doctrine URL or name", max_length=254, null=True
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="external",
            field=models.BooleanField(
                default=False,
                help_text="Is the event an external event over API",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="fc",
            field=models.CharField(
                help_text="Fleet commander/manager for the event",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="formup_system",
            field=models.CharField(
                help_text="Location for formup", max_length=254, null=True
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="host",
            field=models.ForeignKey(
                default=1,
                help_text="Host entity for the event",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="opcalendar.eventhost",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="operation_type",
            field=models.ForeignKey(
                help_text="Event category type",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="opcalendar.eventcategory",
            ),
        ),
    ]
