# Generated by Django 3.1.2 on 2021-03-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opcalendar", "0029_auto_20210315_0600"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingameevents",
            name="event_owner_id",
            field=models.IntegerField(null=True),
        ),
    ]
