# Generated by Django 3.1.2 on 2021-03-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcalendar', '0029_auto_20210314_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_visibility',
        ),
        migrations.AddField(
            model_name='event',
            name='event_visibility',
            field=models.ManyToManyField(to='opcalendar.EventVisibility', verbose_name='Authors'),
        ),
    ]
