# Generated by Django 4.2.23 on 2026-02-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcalendar', '0029_add_fortnightly_repeat_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='use_24h',
            field=models.BooleanField(default=True, verbose_name='Use 24-hour time format'),
        ),
    ]
