# Generated by Django 3.1.2 on 2021-03-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcalendar', '0030_auto_20210314_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_visibility',
            field=models.ManyToManyField(to='opcalendar.EventVisibility', verbose_name='Event Visibility'),
        ),
    ]
