# Generated by Django 3.1.2 on 2021-03-15 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opcalendar', '0031_auto_20210315_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_visibility',
            field=models.ForeignKey(default=1, help_text='Visibility filter that dictates who is able to see this event', null=True, on_delete=django.db.models.deletion.CASCADE, to='opcalendar.eventvisibility'),
        ),
        migrations.AlterField(
            model_name='event',
            name='operation_type',
            field=models.ForeignKey(default=1, help_text='Event category type', null=True, on_delete=django.db.models.deletion.CASCADE, to='opcalendar.eventcategory'),
        ),
    ]
