# Generated by Django 3.1.2 on 2021-03-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('opcalendar', '0031_auto_20210314_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventvisibility',
            name='restricted_to_group',
            field=models.ManyToManyField(blank=True, help_text='Restrict event visibility to the following group(s) ...', to='auth.Group'),
        ),
    ]
