# Generated by Django 3.1.2 on 2021-03-15 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opcalendar', '0032_auto_20210315_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_visibility',
            field=models.ForeignKey(help_text='Visibility filter that dictates who is able to see this event', null=True, on_delete=django.db.models.deletion.CASCADE, to='opcalendar.eventvisibility'),
        ),
    ]
