# Generated by Django 3.1.2 on 2021-03-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcalendar', '0033_auto_20210314_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_visibility',
            field=models.ManyToManyField(to='opcalendar.EventVisibility'),
        ),
    ]
