# Generated by Django 3.1.2 on 2021-03-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_remove_fleetup_permission'),
        ('opcalendar', '0035_auto_20210314_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventvisibility',
            name='restricted_to_state',
            field=models.ManyToManyField(blank=True, help_text='Restrict event visibility to the following state(s) ...', related_name='eventvisibility_require_states', to='authentication.State'),
        ),
    ]
