# Generated by Django 3.1.2 on 2021-03-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0017_remove_fleetup_permission'),
        ('opcalendar', '0036_eventvisibility_restricted_to_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventvisibility',
            name='restricted_to_group',
            field=models.ManyToManyField(blank=True, help_text='The group(s) that will be able to see this event visibility type ...', related_name='eventvisibility_require_groups', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='eventvisibility',
            name='restricted_to_state',
            field=models.ManyToManyField(blank=True, help_text='The state(s) that will be able to see this event visibility type ...', related_name='eventvisibility_require_states', to='authentication.State'),
        ),
    ]
