# Generated by Django 3.1.2 on 2021-03-14 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opcalendar', '0037_auto_20210314_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='visibility',
        ),
    ]
