# Generated by Django 3.1.2 on 2021-03-14 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opcalendar', '0038_remove_event_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventvisibility',
            name='discord_signals',
            field=models.ForeignKey(default=1, help_text='The AA host that will be used for the pulled events', on_delete=django.db.models.deletion.CASCADE, to='opcalendar.eventsignal'),
        ),
    ]
