# Generated by Django 3.1.2 on 2021-03-14 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opcalendar', '0039_eventvisibility_discord_signals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventvisibility',
            name='discord_signals',
        ),
    ]
