# Generated by Django 3.1.2 on 2021-03-14 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opcalendar', '0040_remove_eventvisibility_discord_signals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventvisibility',
            options={'verbose_name': 'Event Visibility', 'verbose_name_plural': 'Event Visibilities'},
        ),
        migrations.AddField(
            model_name='eventvisibility',
            name='ignore_past_fleets',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventvisibility',
            name='webhook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='opcalendar.webhook'),
        ),
        migrations.DeleteModel(
            name='EventSignal',
        ),
    ]
