# Generated by Django 3.1.2 on 2021-03-14 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0012_index_additions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opcalendar', '0042_auto_20210314_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the event was created'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Description text for the operation', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='doctrine',
            field=models.CharField(blank=True, default='', help_text='Doctrine URL or name', max_length=254),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(help_text='Event end date and time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eve_character',
            field=models.ForeignKey(help_text='Character used to create the event', null=True, on_delete=django.db.models.deletion.SET_NULL, to='eveonline.evecharacter'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_visibility',
            field=models.ForeignKey(help_text='Visibility filter that dictates who is able to see this event', null=True, on_delete=django.db.models.deletion.CASCADE, to='opcalendar.eventvisibility'),
        ),
        migrations.AlterField(
            model_name='event',
            name='external',
            field=models.BooleanField(default=False, help_text='Is the event an external event over API'),
        ),
        migrations.AlterField(
            model_name='event',
            name='fc',
            field=models.CharField(default='', help_text='Fleet commander/manager for the event', max_length=254),
        ),
        migrations.AlterField(
            model_name='event',
            name='formup_system',
            field=models.CharField(blank=True, default='', help_text='Location for formup', max_length=254),
        ),
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.ForeignKey(default=1, help_text='Host entity for the event', on_delete=django.db.models.deletion.CASCADE, to='opcalendar.eventhost'),
        ),
        migrations.AlterField(
            model_name='event',
            name='operation_type',
            field=models.ForeignKey(help_text='Event category type', on_delete=django.db.models.deletion.CASCADE, to='opcalendar.eventcategory'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(help_text='Event start date and time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Title for the event', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(help_text='User who created the event', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='name',
            field=models.CharField(help_text='Name for the category', max_length=150),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='ticker',
            field=models.CharField(help_text='Ticker for the category', max_length=10),
        ),
        migrations.AlterField(
            model_name='eventvisibility',
            name='ignore_past_fleets',
            field=models.BooleanField(default=True, help_text='Should we ignore fleet signals that are in the past'),
        ),
        migrations.AlterField(
            model_name='eventvisibility',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this visibility filter is active'),
        ),
        migrations.AlterField(
            model_name='eventvisibility',
            name='name',
            field=models.CharField(help_text='Name for the visibility filter', max_length=150),
        ),
        migrations.AlterField(
            model_name='eventvisibility',
            name='webhook',
            field=models.ForeignKey(help_text='Webhook to send over notifications about these fleet types', null=True, on_delete=django.db.models.deletion.CASCADE, to='opcalendar.webhook'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Is the webhook enabled?'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='name',
            field=models.CharField(help_text='Name for this webhook', max_length=150),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='webhook_url',
            field=models.CharField(help_text='Webhook URL', max_length=500),
        ),
    ]
