# Generated by Django 3.1.2 on 2021-03-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opcalendar', '0043_auto_20210314_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventhost',
            name='external',
            field=models.BooleanField(default=False, help_text='External hosts are for NPSI API imports. Checking this box will hide the host in the manual event form.'),
        ),
    ]
